#!/usr/bin/node
"use strict";
const displayDmenu = require("./src/utils/display-dmenu");
const changeAudioStreamLevels = require('./src/changeAudioStreamLevels.js');
const changeDefaultAudioDevice = require('./src/changeDefaultAudioDevice.js');
const changeStreamDevice = require('./src/changeStreamDevice');

displayDmenu('default-audio-device\naudio-stream-levels\nchange-stream-device').then(selectedOption => {
    if(selectedOption === 'default-audio-device'){
      changeDefaultAudioDevice();
    } else if(selectedOption === 'audio-stream-levels') {
      changeAudioStreamLevels();
    } else if(selectedOption === 'change-stream-device'){
      changeStreamDevice();
    }
});